compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_hostfile: /home/aiscuser/hostfile
  deepspeed_multinode_launcher: pdsh
  gradient_accumulation_steps: 4
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_process_ip: 10.13.37.178
main_process_port: 34124
main_training_function: main
mixed_precision: fp16
num_machines: 2
num_processes: 32
rdzv_backend: static
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
